<h4>Astreoids Risk Analysis Dashboard (ARAD) Risk Model Notebook<h4> 
<p>This notebook will be used to test a Random Forrest model.</p>

In [1]:
import os 
import sqlite3 
import pandas as pd

In [2]:
db_path = os.path.join("..","astreoid_risk_anaylzed.db")
conn = sqlite3.connect(db_path) 
df = pd.read_sql("SELECT * FROM astreoids WHERE close_date",conn)

In [3]:
df.head(3)

,close_date,astreoid_name,max_diameter,min_diameter,absoulte_magnitude,min_distance_km,min_distance_au,speed_kmh,potentially_hazardous,sentry_object
0,2026-05-24,(2010 SX11),0.065169,0.029144,24.8,6.167525e+07,0.412274,26751.080414,0,0
1,2026-05-23,(2000 UR16),0.098637,0.044112,23.9,7.445741e+07,0.497717,74366.251824,0,0
2,2026-05-22,(2011 UD256),0.622358,0.278327,19.9,6.209497e+07,0.415079,128183.818181,0,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   close_date             380 non-null    object
 1   astreoid_name          380 non-null    object
 2   max_diameter           380 non-null    float64
 3   min_diameter           380 non-null    float64
 4   absoulte_magnitude     380 non-null    float64
 5   min_distance_km        380 non-null    float64
 6   min_distance_au        380 non-null    float64
 7   speed_kmh              380 non-null    float64
 8   potentially_hazardous  380 non-null    int64
 9   sentry_object          380 non-null    int64
dtypes: float64(6), int64(2), object(2)
memory usage: 29.8+ KB

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report , confusion_matrix 
from sklearn.model_selection import train_test_split

In [6]:
X = df.drop(["close_date","astreoid_name","min_distance_km","potentially_hazardous"],axis=1)  
Y = df["potentially_hazardous"]

In [7]:
x_train , x_test , y_train , y_test = train_test_split(X,Y,test_size=0.3,random_state=22)

In [8]:
forest = RandomForestClassifier(n_estimators=200,class_weight="balanced",max_depth=5,min_samples_leaf=5,random_state=22) 
model = forest.fit(x_train,y_train) 

predict = model.predict(x_test)

print(model.score(x_test,y_test))
print(model.score(x_train,y_train))

0.7894736842105263
0.8834586466165414

In [9]:
print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      0.76      0.86        98
           1       0.40      1.00      0.57        16

    accuracy                           0.79       114
   macro avg       0.70      0.88      0.72       114
weighted avg       0.92      0.79      0.82       114

In [10]:
confusion_matrix(y_test,predict)

array([[74, 24],
       [ 0, 16]])

In [11]:
"""
! Google Gemini was used to export the model in .pkl format.
"""
import joblib 

joblib.dump(forest,"model.pkl")

['model.pkl']

In [12]:
X

,max_diameter,min_diameter,absoulte_magnitude,min_distance_au,speed_kmh,sentry_object
0,0.065169,0.029144,24.80,0.412274,26751.080414,0
1,0.098637,0.044112,23.90,0.497717,74366.251824,0
2,0.622358,0.278327,19.90,0.415079,128183.818181,0
3,0.950692,0.425163,18.98,0.133969,34309.439107,0
4,0.032662,0.014607,26.30,0.177307,13356.758942,0
...,...,...,...,...,...,...
375,0.027167,0.012149,26.70,0.256628,54026.956519,0
376,0.685551,0.306588,19.69,0.046982,48479.178032,0
377,0.235527,0.105331,22.01,0.160679,46465.960252,0
378,0.179490,0.080270,22.60,0.493023,97713.597702,0
379,0.027167,0.012149,26.70,0.256628,54026.956519,0